-- STUDENTS table
insert all
    into STUDENTS values (1, 'Samantha')
    into STUDENTS values (2, 'Julia')
    into STUDENTS values (3, 'Britney')
    into STUDENTS values (4, 'Kristeen')
    into STUDENTS values (5, 'Dyana')
    into STUDENTS values (6, 'Jenny')
    into STUDENTS values (7, 'Christene')
    into STUDENTS values (8, 'Meera')
    into STUDENTS values (9, 'Priya')
    into STUDENTS values (10, 'Priyanka')
    into STUDENTS values (11, 'Paige')
    into STUDENTS values (12, 'Jane')
    into STUDENTS values (13, 'Belvet')
    into STUDENTS values (14, 'Scarlet')
    into STUDENTS values (15, 'Salma')
    into STUDENTS values (16, 'Amanda')
    into STUDENTS values (17, 'Maria')
    into STUDENTS values (18, 'Stuart')
    into STUDENTS values (19, 'Aamina')
    into STUDENTS values (20, 'Amina')
select * from dual;

-- FRIENDS table
insert all
    into FRIENDS values (1, 14)
    into FRIENDS values (2, 15)
    into FRIENDS values (3, 18)
    into FRIENDS values (4, 19)
    into FRIENDS values (5, 20)
    into FRIENDS values (6, 5)
    into FRIENDS values (7, 6)
    into FRIENDS values (8, 7)
    into FRIENDS values (9, 8)
    into FRIENDS values (10, 1)
    into FRIENDS values (11, 2)
    into FRIENDS values (12, 3)
    into FRIENDS values (13, 4)
    into FRIENDS values (14, 9)
    into FRIENDS values (15, 10)
    into FRIENDS values (16, 11)
    into FRIENDS values (17, 12)
    into FRIENDS values (18, 13)
    into FRIENDS values (19, 16)
    into FRIENDS values (20, 17)
select * from dual;

-- PACKAGES table
insert all
    into PACKAGES values (1, 15.5)
    into PACKAGES values (2, 15.6)
    into PACKAGES values (3, 16.7)
    into PACKAGES values (4, 18.8)
    into PACKAGES values (5, 31.5)
    into PACKAGES values (6, 45)
    into PACKAGES values (7, 47)
    into PACKAGES values (8, 46)
    into PACKAGES values (9, 39)
    into PACKAGES values (10, 11.1)
    into PACKAGES values (11, 12.1)
    into PACKAGES values (12, 13.1)
    into PACKAGES values (13, 14.1)
    into PACKAGES values (14, 15.1)
    into PACKAGES values (15, 17.1)
    into PACKAGES values (16, 21.1)
    into PACKAGES values (17, 31.1)
    into PACKAGES values (18, 13.15)
    into PACKAGES values (19, 33.33)
    into PACKAGES values (20, 22.16)
select * from dual;
